package oss.roost.mobile.store

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Minimal AES/GCM box backed by an AndroidKeyStore key (API.md §1 / DESIGN §6: token in
 * Keystore-encrypted prefs, never plaintext).
 *
 * WHY this and not androidx.security:security-crypto: that artifact (EncryptedSharedPrefs)
 * is deprecated and pulls in Tink — against the zero-dep budget. A single hardware-backed
 * AES key + GCM gives the same guarantee in ~50 lines: encrypt() returns base64(iv|ct) and
 * decrypt() reverses it. The key never leaves the keystore.
 */
class KeystoreBox(private val alias: String = "roost_mobile_token_key") {

    private val keyStore: KeyStore =
        KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }

    private fun secretKey(): SecretKey {
        (keyStore.getEntry(alias, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }
        val gen = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        gen.init(
            KeyGenParameterSpec.Builder(
                alias,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build()
        )
        return gen.generateKey()
    }

    /** @return base64( IV(12) || ciphertext+tag ). */
    fun encrypt(plaintext: String): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())
        val iv = cipher.iv // GCM IV is generated by the provider (12 bytes)
        val ct = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
        val out = ByteArray(iv.size + ct.size)
        System.arraycopy(iv, 0, out, 0, iv.size)
        System.arraycopy(ct, 0, out, iv.size, ct.size)
        return android.util.Base64.encodeToString(out, android.util.Base64.NO_WRAP)
    }

    /** Reverse of [encrypt]; returns null if the blob is corrupt or the key rotated. */
    fun decrypt(blob: String): String? = try {
        val bytes = android.util.Base64.decode(blob, android.util.Base64.NO_WRAP)
        val iv = bytes.copyOfRange(0, IV_LEN)
        val ct = bytes.copyOfRange(IV_LEN, bytes.size)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, secretKey(), GCMParameterSpec(GCM_TAG_BITS, iv))
        String(cipher.doFinal(ct), Charsets.UTF_8)
    } catch (_: Exception) {
        null
    }

    private companion object {
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val IV_LEN = 12
        const val GCM_TAG_BITS = 128
    }
}
